[package]
name = "haylcon"
version = "0.1.0"
edition = "2021"
authors = [ "PwnWriter < hey@pwnwriter.xyz >", "ashokcpg < hey@ashokcpg.com >" ]
description = "Blazingly fast tool to grab screenshots of url/webpages from terminal."
readme = "README.md"
repository = "https://github.com/bytehunt/haylcon"
homepage = "https://github.com/bytehunt/haylcon.git"
license = "MIT"
keywords = ["screenshots", "bug-bounty", "recon", "pwn", "OSINT" ]
categories = ["accessibility", "command-line-utilities", "CLI" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.8", features = ["full"] }
url = "2.3.1"
reqwest = "0.11.14"
tokio = { version = "1.26.0", features = ["full"] }
chromiumoxide = {  version = "0.5.0", features = ["tokio-runtime"], default-features = false }
futures = "0.3.27"

[profile.release]
lto = true
panic = "abort"

